### ISSUE TITLE
Custom encoding function?

### ISSUE THREAD

**Issue by rauchg** [ben-eb/postcss-reduce-idents#7]
Hey! Thanks for an awesome set of postcss modules.

I'm looking to use this module for CSS isolation. In particular, I need to rewrite users' animation names dynamically (for example, adding a prefix).

This module gets extremely close to what I need, but the replacement strategy is always constant (in the spirit of minification).

Would you consider a modification to this, namely a parameter for a user-defined function?

**Comment by ben-eb** [comment]
Sure thing, PR welcome. :+1:

**Comment by rauchg** [comment]
@ben-eb Done. Please let me know if you have any feedback. Thank you =]

**Comment by ben-eb** [comment]
Fixed in https://github.com/ben-eb/postcss-reduce-idents/commit/ba7f09fff628ca57a01fe155b2d4de6a744fcad7.
